imports_granularity = "Module"
group_imports = "StdExternalCrate"
imports_layout = "HorizontalVertical"
match_arm_blocks = true
match_block_trailing_comma = true
overflow_delimited_expr = true
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
normalize_comments = true
format_code_in_doc_comments = true
